### PR TITLE
Update to mainnet config

### PR DESCRIPTION
**Pull request by Overseven**

### CODE REVIEW

**Comment by TamtamHero** [comment]
Can you please allow owner edits on this PR ?

**Comment by Overseven** [comment]
> Can you please allow owner edits on this PR?

Checkbox "Allow edits by maintainers" has already been checked.
Or do you mean something else?

**Comment by Overseven** [comment]
I send you an invite to get the maintainer role of our repository

**Comment by TamtamHero** [comment]
thanks !

**Pull request merged**
